version: '3'

volumes:
  pg_data_userbot:
  pgadmin_data:

services:
  db_postgres:
    container_name: db_userbot
    image: postgres:14-alpine
    env_file: .env
    volumes:
      -   pg_data_userbot:/var/lib/postgresql/data
    ports:
      - "25432:5432"
    restart: always


#  pgadmin:
#    container_name: pgadmin_container_deposit
#    image: dpage/pgadmin4
#    env_file: .env
#    environment:
#      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
#      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
#
#    depends_on:
#      - db_postgres
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    restart: always
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 1G
